name: Deploy DotNet project to TimerStartPipelineFunction App

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: 'https://timerstartpipelinefunction-onel03.azurewebsites.net'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.\SchedulePipelineFunctionApp'       # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd '.\${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./bin
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/bin'
        publish-profile: '<publishData><publishProfile profileName="TimerStartPipelineFunction-onel03 - Web Deploy" publishMethod="MSDeploy" publishUrl="timerstartpipelinefunction-onel03.scm.azurewebsites.net:443" msdeploySite="TimerStartPipelineFunction-onel03" userName="$TimerStartPipelineFunction-onel03" userPWD="RnAu2Nb1q9BsE0wtogrW8N6mY1l1tcYfGtuvvfl83fBygck9vAkSWKzxQo0c" destinationAppUrl="http://timerstartpipelinefunction-onel03.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="TimerStartPipelineFunction-onel03 - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-bn1-125.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="TimerStartPipelineFunction-onel03\$TimerStartPipelineFunction-onel03" userPWD="RnAu2Nb1q9BsE0wtogrW8N6mY1l1tcYfGtuvvfl83fBygck9vAkSWKzxQo0c" destinationAppUrl="http://timerstartpipelinefunction-onel03.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="TimerStartPipelineFunction-onel03 - Zip Deploy" publishMethod="ZipDeploy" publishUrl="timerstartpipelinefunction-onel03.scm.azurewebsites.net:443" userName="$TimerStartPipelineFunction-onel03" userPWD="RnAu2Nb1q9BsE0wtogrW8N6mY1l1tcYfGtuvvfl83fBygck9vAkSWKzxQo0c" destinationAppUrl="http://timerstartpipelinefunction-onel03.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'